.TH "config.h" 3 "Lundi 4 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZ_M\fP   10"
.br
.ti -1c
.RI "#define \fBMAX_SHT\fP   32767"
.br
.ti -1c
.RI "#define \fBERROR_NULL\fP(a,  str)   if (a == NULL) {fprintf(stderr, '%s\\n', str); return EXIT_FAILURE;}"
.br
.ti -1c
.RI "#define \fBERROR_SYS\fP(a,  str)   if (a < 0) {fprintf(stderr, '%s\\n', str); return EXIT_FAILURE;}"
.br
.ti -1c
.RI "#define \fBERROR_NULLCHAR\fP(a,  str)   if (a == NULL) {fprintf(stderr, '%s\\n', str); return NULL;}"
.br
.ti -1c
.RI "#define \fBERROR_SYSCHAR\fP(a,  str)   if (a < 0) {fprintf(stderr, '%s\\n', str); return NULL;}"
.br
.ti -1c
.RI "#define \fBERROR_EOF\fP(a,  str)   if (a == EOF) {fprintf(stderr, '%s\\n', str); return EXIT_FAILURE;}"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBSIZE\fP"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define ERROR_EOF(a, str)   if (a == EOF) {fprintf(stderr, '%s\\n', str); return EXIT_FAILURE;}"

.SS "#define ERROR_NULL(a, str)   if (a == NULL) {fprintf(stderr, '%s\\n', str); return EXIT_FAILURE;}"

.SS "#define ERROR_NULLCHAR(a, str)   if (a == NULL) {fprintf(stderr, '%s\\n', str); return NULL;}"

.SS "#define ERROR_SYS(a, str)   if (a < 0) {fprintf(stderr, '%s\\n', str); return EXIT_FAILURE;}"

.SS "#define ERROR_SYSCHAR(a, str)   if (a < 0) {fprintf(stderr, '%s\\n', str); return NULL;}"

.SS "#define MAX_SHT   32767"

.SS "#define SIZ_M   10"

.SH "Documentation des variables"
.PP 
.SS "int SIZE"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
