.TH B TREE INSERT 1
.SH NAME
B TREE INSERT \- Methode d'insertion dans un arbre
.SH SYNOPSIS
.B #include "LibBT.h"
.br

.br
.B void insertBulkData(int opt, Node *rac, char* namefile);
.br
.SH DESCRIPTION
Btree est une structure d'arbre triee, equilibree, stocke par association de couple de cle et valeur.
.br

La fonction insertBilData() permet d'inserer le fichier donnee un argument dans l'arbre, si l'option memoire est choisie alors le contenu du fichier sera chargée en memoire sinon ce sera le nom du fichier
L'argument rac est l'arbre dans lequel il faut inserer le nouveau noeud

.SH "SEE ALSO"
.BR create(1)
.BR loadInMemory(1)
.BR storeToDisk(1)
.BR bt(1)
