.TH "Node" 3 "Mardi 5 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LibBT\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBisLeaf\fP"
.br
.ti -1c
.RI "short \fBvalue1\fP"
.br
.ti -1c
.RI "short \fBvalue2\fP"
.br
.ti -1c
.RI "short \fBs1\fP"
.br
.ti -1c
.RI "short \fBs2\fP"
.br
.ti -1c
.RI "short \fBs3\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBleft\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBmiddle\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBright\fP"
.br
.ti -1c
.RI "struct \fBNode\fP * \fBfather\fP"
.br
.ti -1c
.RI "short \fBlevel\fP"
.br
.ti -1c
.RI "short \fBindic\fP"
.br
.in -1c
.SH "Documentation des données membres"
.PP 
.SS "struct \fBNode\fP* Node::father"
null à la racine 
.SS "short Node::indic"
level_indice 
.SS "int Node::isLeaf"
savoir si cest une feuille 
.SS "struct \fBNode\fP* Node::left"

.SS "short Node::level"

.SS "struct \fBNode\fP * Node::middle"

.SS "struct \fBNode\fP * Node::right"
only for node 
.SS "short Node::s1"

.SS "short Node::s2"

.SS "short Node::s3"
for disk 
.SS "short Node::value1"

.SS "short Node::value2"
cases 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
