.TH "relation.h" 3 "Lundi 4 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
relation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRELATION_H_\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "char * \fBconcateneNameDirectory\fP (char *path, int number)"
.br
.ti -1c
.RI "char * \fBconcateneNameDirectoryDirectory\fP (char *pathParent, int path)"
.br
.ti -1c
.RI "char * \fBconcateneNameFile\fP (char *pathDirectory, char *nameFile, int numberFile)"
.br
.ti -1c
.RI "char * \fBconcateneChar\fP (char *pathDirectory, char *path)"
.br
.ti -1c
.RI "int \fBlastNumberNameFile\fP (char *path)"
.br
.ti -1c
.RI "int \fBcountFileInDirectory\fP (char *path)"
.br
.ti -1c
.RI "int \fBcreateDirectory\fP (char *path)"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define RELATION_H_"

.SH "Documentation des fonctions"
.PP 
.SS "char* concateneChar (char * pathDirectory, char * path)"
concatener les arguments pour former le nom du fichier 
.PP
\fBParamètres:\fP
.RS 4
\fIpathDirectory\fP chemin du dossier 
.br
\fInameFile\fP chemin du sous dossier 
.RE
.PP
\fBRenvoie:\fP
.RS 4
le resultat de la concatenation 
.RE
.PP

.SS "char* concateneNameDirectory (char * path, int number)"
concatener les arguments pour former le nom du repertoire 
.PP
\fBParamètres:\fP
.RS 4
\fIpath\fP chemin du dossier 
.br
\fInumber\fP indice du dossier 
.RE
.PP
\fBRenvoie:\fP
.RS 4
le resultat de la concatenation 
.RE
.PP

.SS "char* concateneNameDirectoryDirectory (char * pathParent, int path)"
concatener les arguments pour former le nom du repertoire 
.PP
\fBParamètres:\fP
.RS 4
\fIpathParent\fP chemin du dossier parent 
.br
\fIpath\fP chemin du dossier courant 
.RE
.PP
\fBRenvoie:\fP
.RS 4
le resultat de la concatenation 
.RE
.PP

.SS "char* concateneNameFile (char * pathDirectory, char * nameFile, int numberFile)"
concatener les arguments pour former le nom du fichier 
.PP
\fBParamètres:\fP
.RS 4
\fIpathDirectory\fP chemin du dossier 
.br
\fInameFile\fP name de ce fichier 
.br
\fInumber\fP indice du fichier 
.RE
.PP
\fBRenvoie:\fP
.RS 4
le resultat de la concatenation 
.RE
.PP

.SS "int countFileInDirectory (char * path)"
compter le nombre de fichier dans le repertoire 
.PP
\fBParamètres:\fP
.RS 4
\fIpath\fP chemin du dossier 
.RE
.PP
\fBRenvoie:\fP
.RS 4
nombre de fichier 
.RE
.PP

.SS "int createDirectory (char * path)"
creer le repertoire 
.PP
\fBParamètres:\fP
.RS 4
\fIpath\fP chemin du dossier 
.RE
.PP
\fBRenvoie:\fP
.RS 4
erreur eventuelle 
.RE
.PP

.SS "int lastNumberNameFile (char * path)"
connaitre le numero du dernier fichier dans ce repertoire 
.PP
\fBParamètres:\fP
.RS 4
\fIpath\fP chemin du dossier 
.RE
.PP
\fBRenvoie:\fP
.RS 4
nombre du dernier fichier 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
